name: HawkeyeStock
favicon: null
layout_spectrum: 0.11196696967817843
typography_spectrum: 0.9229462910443544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9707617629319429
  lightness: 0.7520007542334497
  saturation: 0.5465942469891161
  rhythmicContrast: 0.9589014574885368
purpose: []
